/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Rol = IDL.Variant({ 'calisan' : IDL.Null, 'yonetici' : IDL.Null });
export const Yetki = IDL.Record({
  'personelYonetimi' : IDL.Bool,
  'duyuruYonetimi' : IDL.Bool,
  'raporGorme' : IDL.Bool,
  'gorevYonetimi' : IDL.Bool,
});
export const Bilgi = IDL.Record({
  'id' : IDL.Text,
  'rol' : Rol,
  'userId' : IDL.Principal,
  'aktifMi' : IDL.Bool,
  'yetkiler' : Yetki,
  'adSoyad' : IDL.Text,
  'companyId' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CompanyRole = IDL.Variant({
  'Employee' : IDL.Null,
  'Owner' : IDL.Null,
  'Manager' : IDL.Null,
});
export const Time = IDL.Int;
export const Bilgi__2 = IDL.Record({
  'id' : IDL.Text,
  'hedefRol' : IDL.Opt(CompanyRole),
  'olusturmaTarihi' : Time,
  'icerik' : IDL.Text,
  'olusturanId' : IDL.Principal,
  'companyId' : IDL.Text,
});
export const ModulePermissions = IDL.Record({
  'personnelAdd' : IDL.Bool,
  'announcementEdit' : IDL.Bool,
  'taskAdd' : IDL.Bool,
  'announcementView' : IDL.Bool,
  'taskEdit' : IDL.Bool,
  'personnelDelete' : IDL.Bool,
  'taskView' : IDL.Bool,
  'reportView' : IDL.Bool,
  'taskDelete' : IDL.Bool,
  'announcementDelete' : IDL.Bool,
  'personnelEdit' : IDL.Bool,
  'personnelView' : IDL.Bool,
  'announcementAdd' : IDL.Bool,
});
export const UserProfile = IDL.Record({
  'permissions' : ModulePermissions,
  'active' : IDL.Bool,
  'name' : IDL.Text,
  'role' : CompanyRole,
  'companyId' : IDL.Text,
});
export const Durum = IDL.Variant({
  'tamamlandi' : IDL.Null,
  'devamEdiyor' : IDL.Null,
  'beklemede' : IDL.Null,
});
export const Bilgi__1 = IDL.Record({
  'id' : IDL.Text,
  'oncelik' : IDL.Nat,
  'baslangicTarihi' : Time,
  'olusturanId' : IDL.Principal,
  'aciklama' : IDL.Text,
  'bitisTarihi' : Time,
  'durum' : Durum,
  'sorumluId' : IDL.Principal,
  'companyId' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'aktifPersonelleriListele' : IDL.Func([], [IDL.Vec(Bilgi)], ['query']),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'davetKoduKullan' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'davetKoduOlustur' : IDL.Func([CompanyRole, Time], [IDL.Text], []),
  'duyuruKaydet' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(CompanyRole)],
      [IDL.Bool],
      [],
    ),
  'duyuruSil' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'duyurulariListele' : IDL.Func([], [IDL.Vec(Bilgi__2)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'gorevGuncelle' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, Durum],
      [IDL.Bool],
      [],
    ),
  'gorevKaydet' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Principal, Time, Time, Durum],
      [IDL.Bool],
      [],
    ),
  'gorevSil' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'gorevleriByDurum' : IDL.Func([Durum], [IDL.Vec(Bilgi__1)], ['query']),
  'gorevleriListele' : IDL.Func([], [IDL.Vec(Bilgi__1)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'kurumKaydet' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'kurumVarmi' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'personelGetir' : IDL.Func([IDL.Text], [Bilgi], ['query']),
  'personelGuncelle' : IDL.Func(
      [IDL.Text, IDL.Text, Rol, Yetki, IDL.Bool],
      [IDL.Bool],
      [],
    ),
  'personelKaydet' : IDL.Func(
      [IDL.Text, IDL.Text, Rol, Yetki, IDL.Principal],
      [IDL.Bool],
      [],
    ),
  'personelListele' : IDL.Func([], [IDL.Vec(Bilgi)], ['query']),
  'personelSil' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'raporAl' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Rol = IDL.Variant({ 'calisan' : IDL.Null, 'yonetici' : IDL.Null });
  const Yetki = IDL.Record({
    'personelYonetimi' : IDL.Bool,
    'duyuruYonetimi' : IDL.Bool,
    'raporGorme' : IDL.Bool,
    'gorevYonetimi' : IDL.Bool,
  });
  const Bilgi = IDL.Record({
    'id' : IDL.Text,
    'rol' : Rol,
    'userId' : IDL.Principal,
    'aktifMi' : IDL.Bool,
    'yetkiler' : Yetki,
    'adSoyad' : IDL.Text,
    'companyId' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CompanyRole = IDL.Variant({
    'Employee' : IDL.Null,
    'Owner' : IDL.Null,
    'Manager' : IDL.Null,
  });
  const Time = IDL.Int;
  const Bilgi__2 = IDL.Record({
    'id' : IDL.Text,
    'hedefRol' : IDL.Opt(CompanyRole),
    'olusturmaTarihi' : Time,
    'icerik' : IDL.Text,
    'olusturanId' : IDL.Principal,
    'companyId' : IDL.Text,
  });
  const ModulePermissions = IDL.Record({
    'personnelAdd' : IDL.Bool,
    'announcementEdit' : IDL.Bool,
    'taskAdd' : IDL.Bool,
    'announcementView' : IDL.Bool,
    'taskEdit' : IDL.Bool,
    'personnelDelete' : IDL.Bool,
    'taskView' : IDL.Bool,
    'reportView' : IDL.Bool,
    'taskDelete' : IDL.Bool,
    'announcementDelete' : IDL.Bool,
    'personnelEdit' : IDL.Bool,
    'personnelView' : IDL.Bool,
    'announcementAdd' : IDL.Bool,
  });
  const UserProfile = IDL.Record({
    'permissions' : ModulePermissions,
    'active' : IDL.Bool,
    'name' : IDL.Text,
    'role' : CompanyRole,
    'companyId' : IDL.Text,
  });
  const Durum = IDL.Variant({
    'tamamlandi' : IDL.Null,
    'devamEdiyor' : IDL.Null,
    'beklemede' : IDL.Null,
  });
  const Bilgi__1 = IDL.Record({
    'id' : IDL.Text,
    'oncelik' : IDL.Nat,
    'baslangicTarihi' : Time,
    'olusturanId' : IDL.Principal,
    'aciklama' : IDL.Text,
    'bitisTarihi' : Time,
    'durum' : Durum,
    'sorumluId' : IDL.Principal,
    'companyId' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'aktifPersonelleriListele' : IDL.Func([], [IDL.Vec(Bilgi)], ['query']),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'davetKoduKullan' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'davetKoduOlustur' : IDL.Func([CompanyRole, Time], [IDL.Text], []),
    'duyuruKaydet' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(CompanyRole)],
        [IDL.Bool],
        [],
      ),
    'duyuruSil' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'duyurulariListele' : IDL.Func([], [IDL.Vec(Bilgi__2)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'gorevGuncelle' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, Durum],
        [IDL.Bool],
        [],
      ),
    'gorevKaydet' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Principal, Time, Time, Durum],
        [IDL.Bool],
        [],
      ),
    'gorevSil' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'gorevleriByDurum' : IDL.Func([Durum], [IDL.Vec(Bilgi__1)], ['query']),
    'gorevleriListele' : IDL.Func([], [IDL.Vec(Bilgi__1)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'kurumKaydet' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'kurumVarmi' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'personelGetir' : IDL.Func([IDL.Text], [Bilgi], ['query']),
    'personelGuncelle' : IDL.Func(
        [IDL.Text, IDL.Text, Rol, Yetki, IDL.Bool],
        [IDL.Bool],
        [],
      ),
    'personelKaydet' : IDL.Func(
        [IDL.Text, IDL.Text, Rol, Yetki, IDL.Principal],
        [IDL.Bool],
        [],
      ),
    'personelListele' : IDL.Func([], [IDL.Vec(Bilgi)], ['query']),
    'personelSil' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'raporAl' : IDL.Func([IDL.Text], [IDL.Text], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };