/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bilgi {
  'id' : string,
  'rol' : Rol,
  'userId' : Principal,
  'aktifMi' : boolean,
  'yetkiler' : Yetki,
  'adSoyad' : string,
  'companyId' : string,
}
export interface Bilgi__1 {
  'id' : string,
  'oncelik' : bigint,
  'baslangicTarihi' : Time,
  'olusturanId' : Principal,
  'aciklama' : string,
  'bitisTarihi' : Time,
  'durum' : Durum,
  'sorumluId' : Principal,
  'companyId' : string,
}
export interface Bilgi__2 {
  'id' : string,
  'hedefRol' : [] | [CompanyRole],
  'olusturmaTarihi' : Time,
  'icerik' : string,
  'olusturanId' : Principal,
  'companyId' : string,
}
export type CompanyRole = { 'Employee' : null } |
  { 'Owner' : null } |
  { 'Manager' : null };
export type Durum = { 'tamamlandi' : null } |
  { 'devamEdiyor' : null } |
  { 'beklemede' : null };
export interface ModulePermissions {
  'personnelAdd' : boolean,
  'announcementEdit' : boolean,
  'taskAdd' : boolean,
  'announcementView' : boolean,
  'taskEdit' : boolean,
  'personnelDelete' : boolean,
  'taskView' : boolean,
  'reportView' : boolean,
  'taskDelete' : boolean,
  'announcementDelete' : boolean,
  'personnelEdit' : boolean,
  'personnelView' : boolean,
  'announcementAdd' : boolean,
}
export type Rol = { 'calisan' : null } |
  { 'yonetici' : null };
export type Time = bigint;
export interface UserProfile {
  'permissions' : ModulePermissions,
  'active' : boolean,
  'name' : string,
  'role' : CompanyRole,
  'companyId' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Yetki {
  'personelYonetimi' : boolean,
  'duyuruYonetimi' : boolean,
  'raporGorme' : boolean,
  'gorevYonetimi' : boolean,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'aktifPersonelleriListele' : ActorMethod<[], Array<Bilgi>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'davetKoduKullan' : ActorMethod<[string, string], boolean>,
  'davetKoduOlustur' : ActorMethod<[CompanyRole, Time], string>,
  'duyuruKaydet' : ActorMethod<[string, string, [] | [CompanyRole]], boolean>,
  'duyuruSil' : ActorMethod<[string], boolean>,
  'duyurulariListele' : ActorMethod<[], Array<Bilgi__2>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'gorevGuncelle' : ActorMethod<[string, string, bigint, Durum], boolean>,
  'gorevKaydet' : ActorMethod<
    [string, string, bigint, Principal, Time, Time, Durum],
    boolean
  >,
  'gorevSil' : ActorMethod<[string], boolean>,
  'gorevleriByDurum' : ActorMethod<[Durum], Array<Bilgi__1>>,
  'gorevleriListele' : ActorMethod<[], Array<Bilgi__1>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'kurumKaydet' : ActorMethod<[string, string], boolean>,
  'kurumVarmi' : ActorMethod<[string], boolean>,
  'personelGetir' : ActorMethod<[string], Bilgi>,
  'personelGuncelle' : ActorMethod<
    [string, string, Rol, Yetki, boolean],
    boolean
  >,
  'personelKaydet' : ActorMethod<
    [string, string, Rol, Yetki, Principal],
    boolean
  >,
  'personelListele' : ActorMethod<[], Array<Bilgi>>,
  'personelSil' : ActorMethod<[string], boolean>,
  'raporAl' : ActorMethod<[string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];