/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Bilgi {
    id: string;
    rol: Rol;
    userId: Principal;
    aktifMi: boolean;
    yetkiler: Yetki;
    adSoyad: string;
    companyId: string;
}
export type Time = bigint;
export interface Yetki {
    personelYonetimi: boolean;
    duyuruYonetimi: boolean;
    raporGorme: boolean;
    gorevYonetimi: boolean;
}
export interface Bilgi__1 {
    id: string;
    oncelik: bigint;
    baslangicTarihi: Time;
    olusturanId: Principal;
    aciklama: string;
    bitisTarihi: Time;
    durum: Durum;
    sorumluId: Principal;
    companyId: string;
}
export interface Bilgi__2 {
    id: string;
    hedefRol?: CompanyRole;
    olusturmaTarihi: Time;
    icerik: string;
    olusturanId: Principal;
    companyId: string;
}
export interface UserProfile {
    permissions: ModulePermissions;
    active: boolean;
    name: string;
    role: CompanyRole;
    companyId: string;
}
export interface ModulePermissions {
    personnelAdd: boolean;
    announcementEdit: boolean;
    taskAdd: boolean;
    announcementView: boolean;
    taskEdit: boolean;
    personnelDelete: boolean;
    taskView: boolean;
    reportView: boolean;
    taskDelete: boolean;
    announcementDelete: boolean;
    personnelEdit: boolean;
    personnelView: boolean;
    announcementAdd: boolean;
}
export enum CompanyRole {
    Employee = "Employee",
    Owner = "Owner",
    Manager = "Manager"
}
export enum Durum {
    tamamlandi = "tamamlandi",
    devamEdiyor = "devamEdiyor",
    beklemede = "beklemede"
}
export enum Rol {
    calisan = "calisan",
    yonetici = "yonetici"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    aktifPersonelleriListele(): Promise<Array<Bilgi>>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    davetKoduKullan(kod: string, kullaniciAdi: string): Promise<boolean>;
    davetKoduOlustur(rol: CompanyRole, gecerlilikSuresi: Time): Promise<string>;
    duyuruKaydet(id: string, icerik: string, hedefRol: CompanyRole | null): Promise<boolean>;
    duyuruSil(id: string): Promise<boolean>;
    duyurulariListele(): Promise<Array<Bilgi__2>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    gorevGuncelle(id: string, aciklama: string, oncelik: bigint, durum: Durum): Promise<boolean>;
    gorevKaydet(id: string, aciklama: string, oncelik: bigint, sorumluId: Principal, baslangicTarihi: Time, bitisTarihi: Time, durum: Durum): Promise<boolean>;
    gorevSil(id: string): Promise<boolean>;
    gorevleriByDurum(durum: Durum): Promise<Array<Bilgi__1>>;
    gorevleriListele(): Promise<Array<Bilgi__1>>;
    isCallerAdmin(): Promise<boolean>;
    kurumKaydet(kurumId: string, kurumAdi: string): Promise<boolean>;
    kurumVarmi(id: string): Promise<boolean>;
    personelGetir(id: string): Promise<Bilgi>;
    personelGuncelle(id: string, adSoyad: string, rol: Rol, yetkiler: Yetki, aktifMi: boolean): Promise<boolean>;
    personelKaydet(id: string, adSoyad: string, rol: Rol, yetkiler: Yetki, userId: Principal): Promise<boolean>;
    personelListele(): Promise<Array<Bilgi>>;
    personelSil(id: string): Promise<boolean>;
    raporAl(raporTipi: string): Promise<string>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Bilgi as _Bilgi, Bilgi__1 as _Bilgi__1, Bilgi__2 as _Bilgi__2, CompanyRole as _CompanyRole, Durum as _Durum, ModulePermissions as _ModulePermissions, Rol as _Rol, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, Yetki as _Yetki } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async aktifPersonelleriListele(): Promise<Array<Bilgi>> {
        if (this.processError) {
            try {
                const result = await this.actor.aktifPersonelleriListele();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.aktifPersonelleriListele();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async davetKoduKullan(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.davetKoduKullan(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.davetKoduKullan(arg0, arg1);
            return result;
        }
    }
    async davetKoduOlustur(arg0: CompanyRole, arg1: Time): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.davetKoduOlustur(to_candid_CompanyRole_n8(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.davetKoduOlustur(to_candid_CompanyRole_n8(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async duyuruKaydet(arg0: string, arg1: string, arg2: CompanyRole | null): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.duyuruKaydet(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duyuruKaydet(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async duyuruSil(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.duyuruSil(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duyuruSil(arg0);
            return result;
        }
    }
    async duyurulariListele(): Promise<Array<Bilgi__2>> {
        if (this.processError) {
            try {
                const result = await this.actor.duyurulariListele();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duyurulariListele();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async gorevGuncelle(arg0: string, arg1: string, arg2: bigint, arg3: Durum): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.gorevGuncelle(arg0, arg1, arg2, to_candid_Durum_n22(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gorevGuncelle(arg0, arg1, arg2, to_candid_Durum_n22(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async gorevKaydet(arg0: string, arg1: string, arg2: bigint, arg3: Principal, arg4: Time, arg5: Time, arg6: Durum): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.gorevKaydet(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Durum_n22(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gorevKaydet(arg0, arg1, arg2, arg3, arg4, arg5, to_candid_Durum_n22(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async gorevSil(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.gorevSil(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gorevSil(arg0);
            return result;
        }
    }
    async gorevleriByDurum(arg0: Durum): Promise<Array<Bilgi__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.gorevleriByDurum(to_candid_Durum_n22(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gorevleriByDurum(to_candid_Durum_n22(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async gorevleriListele(): Promise<Array<Bilgi__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.gorevleriListele();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gorevleriListele();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async kurumKaydet(arg0: string, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.kurumKaydet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.kurumKaydet(arg0, arg1);
            return result;
        }
    }
    async kurumVarmi(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.kurumVarmi(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.kurumVarmi(arg0);
            return result;
        }
    }
    async personelGetir(arg0: string): Promise<Bilgi> {
        if (this.processError) {
            try {
                const result = await this.actor.personelGetir(arg0);
                return from_candid_Bilgi_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.personelGetir(arg0);
            return from_candid_Bilgi_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async personelGuncelle(arg0: string, arg1: string, arg2: Rol, arg3: Yetki, arg4: boolean): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.personelGuncelle(arg0, arg1, to_candid_Rol_n29(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.personelGuncelle(arg0, arg1, to_candid_Rol_n29(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async personelKaydet(arg0: string, arg1: string, arg2: Rol, arg3: Yetki, arg4: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.personelKaydet(arg0, arg1, to_candid_Rol_n29(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.personelKaydet(arg0, arg1, to_candid_Rol_n29(this._uploadFile, this._downloadFile, arg2), arg3, arg4);
            return result;
        }
    }
    async personelListele(): Promise<Array<Bilgi>> {
        if (this.processError) {
            try {
                const result = await this.actor.personelListele();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.personelListele();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async personelSil(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.personelSil(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.personelSil(arg0);
            return result;
        }
    }
    async raporAl(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.raporAl(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.raporAl(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Bilgi__1_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bilgi__1): Bilgi__1 {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Bilgi__2_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bilgi__2): Bilgi__2 {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Bilgi_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Bilgi): Bilgi {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_CompanyRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompanyRole): CompanyRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Durum_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Durum): Durum {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Rol_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rol): Rol {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanyRole]): CompanyRole | null {
    return value.length === 0 ? null : from_candid_CompanyRole_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    hedefRol: [] | [_CompanyRole];
    olusturmaTarihi: _Time;
    icerik: string;
    olusturanId: Principal;
    companyId: string;
}): {
    id: string;
    hedefRol?: CompanyRole;
    olusturmaTarihi: Time;
    icerik: string;
    olusturanId: Principal;
    companyId: string;
} {
    return {
        id: value.id,
        hedefRol: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.hedefRol)),
        olusturmaTarihi: value.olusturmaTarihi,
        icerik: value.icerik,
        olusturanId: value.olusturanId,
        companyId: value.companyId
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    permissions: _ModulePermissions;
    active: boolean;
    name: string;
    role: _CompanyRole;
    companyId: string;
}): {
    permissions: ModulePermissions;
    active: boolean;
    name: string;
    role: CompanyRole;
    companyId: string;
} {
    return {
        permissions: value.permissions,
        active: value.active,
        name: value.name,
        role: from_candid_CompanyRole_n15(_uploadFile, _downloadFile, value.role),
        companyId: value.companyId
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    oncelik: bigint;
    baslangicTarihi: _Time;
    olusturanId: Principal;
    aciklama: string;
    bitisTarihi: _Time;
    durum: _Durum;
    sorumluId: Principal;
    companyId: string;
}): {
    id: string;
    oncelik: bigint;
    baslangicTarihi: Time;
    olusturanId: Principal;
    aciklama: string;
    bitisTarihi: Time;
    durum: Durum;
    sorumluId: Principal;
    companyId: string;
} {
    return {
        id: value.id,
        oncelik: value.oncelik,
        baslangicTarihi: value.baslangicTarihi,
        olusturanId: value.olusturanId,
        aciklama: value.aciklama,
        bitisTarihi: value.bitisTarihi,
        durum: from_candid_Durum_n27(_uploadFile, _downloadFile, value.durum),
        sorumluId: value.sorumluId,
        companyId: value.companyId
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    rol: _Rol;
    userId: Principal;
    aktifMi: boolean;
    yetkiler: _Yetki;
    adSoyad: string;
    companyId: string;
}): {
    id: string;
    rol: Rol;
    userId: Principal;
    aktifMi: boolean;
    yetkiler: Yetki;
    adSoyad: string;
    companyId: string;
} {
    return {
        id: value.id,
        rol: from_candid_Rol_n4(_uploadFile, _downloadFile, value.rol),
        userId: value.userId,
        aktifMi: value.aktifMi,
        yetkiler: value.yetkiler,
        adSoyad: value.adSoyad,
        companyId: value.companyId
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Employee: null;
} | {
    Owner: null;
} | {
    Manager: null;
}): CompanyRole {
    return "Employee" in value ? CompanyRole.Employee : "Owner" in value ? CompanyRole.Owner : "Manager" in value ? CompanyRole.Manager : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tamamlandi: null;
} | {
    devamEdiyor: null;
} | {
    beklemede: null;
}): Durum {
    return "tamamlandi" in value ? Durum.tamamlandi : "devamEdiyor" in value ? Durum.devamEdiyor : "beklemede" in value ? Durum.beklemede : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    calisan: null;
} | {
    yonetici: null;
}): Rol {
    return "calisan" in value ? Rol.calisan : "yonetici" in value ? Rol.yonetici : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bilgi>): Array<Bilgi> {
    return value.map((x)=>from_candid_Bilgi_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bilgi__2>): Array<Bilgi__2> {
    return value.map((x)=>from_candid_Bilgi__2_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Bilgi__1>): Array<Bilgi__1> {
    return value.map((x)=>from_candid_Bilgi__1_n25(_uploadFile, _downloadFile, x));
}
function to_candid_CompanyRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompanyRole): _CompanyRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Durum_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Durum): _Durum {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_Rol_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rol): _Rol {
    return to_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompanyRole | null): [] | [_CompanyRole] {
    return value === null ? candid_none() : candid_some(to_candid_CompanyRole_n8(_uploadFile, _downloadFile, value));
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    permissions: ModulePermissions;
    active: boolean;
    name: string;
    role: CompanyRole;
    companyId: string;
}): {
    permissions: _ModulePermissions;
    active: boolean;
    name: string;
    role: _CompanyRole;
    companyId: string;
} {
    return {
        permissions: value.permissions,
        active: value.active,
        name: value.name,
        role: to_candid_CompanyRole_n8(_uploadFile, _downloadFile, value.role),
        companyId: value.companyId
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Durum): {
    tamamlandi: null;
} | {
    devamEdiyor: null;
} | {
    beklemede: null;
} {
    return value == Durum.tamamlandi ? {
        tamamlandi: null
    } : value == Durum.devamEdiyor ? {
        devamEdiyor: null
    } : value == Durum.beklemede ? {
        beklemede: null
    } : value;
}
function to_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Rol): {
    calisan: null;
} | {
    yonetici: null;
} {
    return value == Rol.calisan ? {
        calisan: null
    } : value == Rol.yonetici ? {
        yonetici: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompanyRole): {
    Employee: null;
} | {
    Owner: null;
} | {
    Manager: null;
} {
    return value == CompanyRole.Employee ? {
        Employee: null
    } : value == CompanyRole.Owner ? {
        Owner: null
    } : value == CompanyRole.Manager ? {
        Manager: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
